WIP: basic tap flow
PampaWarro/warrolight pull request #126
Opened 2023-01-20 21:29 UTC by yemel

2023-01-20 22:55 UTC, martinblech requested changes

2023-01-20 22:55 UTC, martinblech commented on server/src/LightController.js
> +  tap(cid) {
s/cid/clientId/?

2023-01-20 22:55 UTC, martinblech commented on server/src/ProgramScheduler.js
> +  tap(cid) {
s/cid/clientId/?

2023-01-20 22:55 UTC, martinblech commented on server/src/light-programs/base-programs/LightProgram.js
> +    this.taps = [];
I would leave this instance var out from the base LightProgram class (it's ever growing in size and very unlikely that all concrete programs will need a full history of all taps).

2023-01-20 22:55 UTC, martinblech commented on server/src/light-programs/base-programs/LightProgram.js
> +  tap(cid) {
Please leave the base implementation of tap() empty. Subclasses can override to hook in on the event.

2023-01-20 22:55 UTC, martinblech commented on server/src/light-programs/base-programs/LightProgram.js
> +  tap(cid) {
s/cid/clientId/

2023-02-07 06:30 UTC, yemel commented
Thanks for the review @martinblech.

@catalanojuan included your comments in his PR. I'll close this and continue working based on it.

2023-02-07 06:30 UTC, closed without merging